#AulaCursoemVideo - Aula 07: exercicio 009
print('======Tabuada======')
v = int(input('Insira o valor desejado: '))
print('{} x {:2} = {}'.format(v, 1, v * 1))
print('{} x {:2} = {}'.format(v, 2, v * 2))
print('{} x {:2} = {}'.format(v, 3, v * 3))
print('{} x {:2} = {}'.format(v, 4, v * 4))
print('{} x {:2} = {}'.format(v, 5, v * 5))
print('{} x {:2} = {}'.format(v, 6, v * 6))
print('{} x {:2} = {}'.format(v, 7, v * 7))
print('{} x {:2} = {}'.format(v, 8, v * 8))
print('{} x {:2} = {}'.format(v, 9, v * 9))
print('{} x {:2} = {}'.format(v, 10, v * 10))
